"""fix mysql enum

Revision ID: 517a245b1ee5
Revises: a8b747ee6eb9
Create Date: 2025-06-05 23:48:27.267900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '517a245b1ee5'
down_revision: Union[str, None] = 'a8b747ee6eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Enum('ONLINE', 'OFFLINE', name='itemstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'status',
               existing_type=sa.Enum('ONLINE', 'OFFLINE', name='itemstatus'),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
