"""add: github oauth

Revision ID: b0a4761741b9
Revises: 629a2bd5720a
Create Date: 2025-06-18 23:39:18.599380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0a4761741b9'
down_revision: Union[str, None] = '629a2bd5720a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('credential', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_password_change', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userauth_auth_type'), 'userauth', ['auth_type'], unique=False)
    op.create_index(op.f('ix_userauth_identifier'), 'userauth', ['identifier'], unique=False)
    op.add_column('user', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.drop_column('user', 'last_password_change')
    op.drop_column('user', 'username')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('last_password_change', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'nickname')
    op.drop_index(op.f('ix_userauth_identifier'), table_name='userauth')
    op.drop_index(op.f('ix_userauth_auth_type'), table_name='userauth')
    op.drop_table('userauth')
    # ### end Alembic commands ###
