"""update enum

Revision ID: b5f7dc6a1c3b
Revises: c812126788f6
Create Date: 2025-04-19 00:41:36.175301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b5f7dc6a1c3b'
down_revision: Union[str, None] = 'c812126788f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###
