"""fix: enum

Revision ID: c812126788f6
Revises: 657109786827
Create Date: 2025-04-18 00:34:43.127638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c812126788f6'
down_revision: Union[str, None] = '657109786827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('ONLINE', 'OFFLINE', name='statusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ONLINE', 'OFFLINE', name='statusenum'),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
